/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortException;

/**
 *
 * @author A-Informático
 */
public class Led extends javax.swing.JFrame {

    /**
     * Creates new form Led
     */
    public Led() {
        initComponents();
        startConecction();
    }
    PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
    private void startConecction(){
        try {
            arduino.arduinoTX("COM4", 9600);
        } catch (ArduinoException ex) {
            System.out.println("Error en la conexión: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        led = new javax.swing.JLabel();
        btnOffOn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        led.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/led-off.png"))); // NOI18N
        jPanel1.add(led, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 250, 320));

        btnOffOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/switch-off.png"))); // NOI18N
        btnOffOn.setBorder(null);
        btnOffOn.setBorderPainted(false);
        btnOffOn.setContentAreaFilled(false);
        btnOffOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOffOn.setFocusPainted(false);
        btnOffOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOffOnMouseClicked(evt);
            }
        });
        jPanel1.add(btnOffOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 420, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOffOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffOnMouseClicked
        if(btnOffOn.isSelected()){
            try {
                arduino.sendData("1");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println("Error enviando datos: " + ex.getMessage());
            }
            led.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/led-on.png")));
            btnOffOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/switch-on.png")));
        }else{
            try {
                arduino.sendData("0");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println("Error enviando datos: " + ex.getMessage());
            }
            led.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/led-off.png")));
            btnOffOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/switch-off.png")));
        }
    }//GEN-LAST:event_btnOffOnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Led().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOffOn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel led;
    // End of variables declaration//GEN-END:variables
}
